<?php
return [
    'Cà phê & matcha' => [
        ['name' => 'Matcha Dừa Xiêm', 'image' => 'matcha-dua-xiem.png', 'price' => '$5.90'],
        ['name' => 'Matcha Bắp-Bi', 'image' => 'matcha-bap-bi.png', 'price' => '$5.90'],
        ['name' => 'IKI Matcha Tàu Hũ', 'image' => 'matcha-tofu.png', 'price' => '$5.90'],
        ['name' => 'IKI Matcha Latte', 'image' => 'matcha-latte.png', 'price' => '$5.90'],
        ['name' => 'Cold Brew Quýt', 'image' => 'cold-brew-quyt.png', 'price' => '$5.90'],
        ['name' => 'Cold Brew Dâu Tằm', 'image' => 'cold-brew-tam.png', 'price' => '$5.90'],
        ['name' => 'Cold Brew Chanh Vàng', 'image' => 'cold-brew-chanh.png', 'price' => '$5.90'],
        ['name' => 'Cà Phê Kem Mây Chanh Vàng', 'image' => 'cafe-kem-may-chanh-vang.png', 'price' => '$5.90'],
        ['name' => 'Latte Nguyên Bản', 'image' => 'latte-nguyen-ban.png', 'price' => '$5.90'],
        ['name' => 'Espresso Sữa Đá', 'image' => 'espresso-sua-da.png', 'price' => '$5.90'],
        ['name' => 'Espresso Đen Đá', 'image' => 'espresso-den-da.png', 'price' => '$5.90'],
        ['name' => 'Americano', 'image' => 'americano.png', 'price' => '$5.90'],
        ['name' => 'Espresso Bạc Xỉu', 'image' => 'espresso-bac-xiu.png', 'price' => '$5.90'],
        ['name' => 'Sô-Cô-La Katinat', 'image' => 'so-co-la.png', 'price' => '$5.90'],
    ],
    'Trà & đồ uống' => [
        ['name' => 'Mê Dừa Non', 'image' => 'me-dua-non.png', 'price' => '$2.90'],
        ['name' => 'Mê Xỉu', 'image' => 'me-xiu.png', 'price' => '$2.90'],
        ['name' => 'Mê Sữa Đá', 'image' => 'me-sua.png', 'price' => '$2.90'],
        ['name' => 'Mê Đen Đá', 'image' => 'me-den.png', 'price' => '$2.90'],
        ['name' => 'Trà Sữa Chôm Chôm', 'image' => 'tra-sua-chom-chom.png', 'price' => '$2.90'],
        ['name' => 'Trà Sữa Oolong Nướng', 'image' => 'tra-sua-oolong-nuong.png', 'price' => '$2.90'],
        ['name' => 'Trà Sữa Oolong Ba Lá', 'image' => 'tra-sua-oolong-ba-la.png', 'price' => '$2.90'],
        ['name' => 'Nhài Sữa Dê Cười', 'image' => 'nhai-sua-de-cuoi.png', 'price' => '$2.90'],
        ['name' => 'Sữa Chua Tằm', 'image' => 'sua-chua-tam.png', 'price' => '$2.90'],
        ['name' => 'Trà Sữa Thanh Hương Camellia', 'image' => 'tra-sua-thanh-huong.png', 'price' => '$2.90'],
        ['name' => 'Cóc Cóc Đắc Đắc', 'image' => 'coc-coc-dac-dac.png', 'price' => '$2.90'],
        ['name' => 'Trà Đào Hồng Đài', 'image' => 'tra-dao-hong-dai.png', 'price' => '$2.90'],
        ['name' => 'Lệ Chi Thanh Trà', 'image' => 'le-chi-thanh-tra.png', 'price' => '$2.90'],
        ['name' => 'Trà Quýt Hạ Du', 'image' => 'tra-quyt.png', 'price' => '$2.90'],
    ],
    'Ăn nhẹ' => [
        ['name' => 'Bánh Tráng Trộn Tôm Hành', 'image' => 'banh-trang-tom-hanh.png', 'price' => '$2.90'],
        ['name' => 'Bánh Tráng Trộn Muối Tỏi', 'image' => 'banh-trang-muoi-toi.png', 'price' => '$2.90'],
    ],
    'Tráng miệng' => [
        ['name' => 'Bông Lan Trứng Muối Sốt Dầu Trứng', 'image' => 'bong-lan-trung-muoi-dau-trung.png', 'price' => '$2.90'],
        ['name' => 'Bánh Phô Mai Tôm & Jerry', 'image' => 'tom-and-jerry.png', 'price' => '$2.90'],
        ['name' => 'Bánh Creme Flan Nhật Bản', 'image' => 'creme-plan.png', 'price' => '$2.90'],
        ['name' => 'Bánh Chuối Nho Khô', 'image' => 'banh-chuoi.png', 'price' => '$2.90'],
        ['name' => 'Bông Lan Trứng Muối', 'image' => 'bong-lan-trung-muoi.png', 'price' => '$2.90'],
        ['name' => 'Bánh Phô Mai Tan Chảy', 'image' => 'pho-mai-tan-chay.png', 'price' => '$2.90'],
        ['name' => 'Bánh Phô Mai Chanh Dây', 'image' => 'pho-mai-chanh-day.png', 'price' => '$2.90'],
    ],
    'Topping' => [
        ['name' => 'Thốt Nốt Cam Vàng', 'image' => 'thot-not.png', 'price' => '$2.90'],
        ['name' => 'Trân Châu Matcha Dừa', 'image' => 'tran-chau-matcha.png', 'price' => '$2.90'],
        ['name' => 'Trân Châu Dừa Thốt Nốt', 'image' => 'tran-chau-dua.png', 'price' => '$2.90'],
        ['name' => 'Tàu Hũ', 'image' => 'tofu.png', 'price' => '$2.90'],
        ['name' => 'Huyền Châu', 'image' => 'huyen-chau.png', 'price' => '$2.90'],
        ['name' => 'Trân Châu Phô Mai Dẻo (4 Viên)', 'image' => 'pho-mai-deo.png', 'price' => '$2.90'],
        ['name' => 'Bánh Flan', 'image' => 'plan.png', 'price' => '$2.90'],
        ['name' => 'Trân Châu Trắng', 'image' => 'tran-chau-trang.png', 'price' => '$2.90'],
        ['name' => 'Thạch Hồng Đài', 'image' => 'thach-hong-dai.png', 'price' => '$2.90'],
    ],
];
